name: energy-training
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=23.0
  - pip:
    - azureml-core==1.54.0
    - azureml-mlflow==1.54.0
    - mlflow==2.8.0
    - xgboost==2.0.2
    - scikit-learn==1.3.2
    - pandas==2.1.3
    - numpy==1.26.2
    - joblib==1.3.2